name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@main
        with:
          armbian_token:               "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:             "trixie"                       # userspace
          armbian_target:              "build"                        # build=image, kernel=kernel
          armbian_board:               "onecloud"                     # build target
          armbian_kernel_branch:       "current"                      # build target
          armbian_ui:                  "minimal"
